// Generated by CoffeeScript 2.5.1
(function() {
  var Client, MessageEmbed, client, config, voiceState;

  ({Client, MessageEmbed} = require('discord.js'));

  config = require('../src/config/config.json');

  client = new Client();

  client.login(config.token);

  client.on("ready", function() {
    return console.log("Ready!");
  });

  voiceState = function(oldMember, newMember) {
    var error;
    if (newMember.member.voice) {
      try {
        return oldMember.member.user.send(new MessageEmbed().setAuthor(oldMember.member.voice.channel.name).setDescription("[Войти в комнату для трансляций](https://discordapp.com/channels/" + oldMember.guild.id + "/" + oldMember.id + ")").setColor("#66CED1"));
      } catch (error1) {
        error = error1;
      }
    }
  };

  client.on('voiceStateUpdate', voiceState);

}).call(this);
